name: Daily Company Tracker

on:
  schedule:
    - cron: '0 12 * * *'  # every day at 12 PM UTC
  workflow_dispatch:

permissions:
  contents: write  # 🔑 allows committing back to repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tracker script
        run: python tracker.py

      - name: Commit and push updated HTML
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Update tracker [auto]" || echo "No changes"
          git push
